### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by aemc** [aemc/bitcoin-testnet3#3]
Good first issue

**Comment by pankaryp** [comment]
Hello there, i am new to open source, can i help?

**Comment by DonaldLika** [comment]
@aemc  Any detail for this issue?

**Comment by aemc** [comment]
@DonaldLika Just update the dependencies in the package.json w/o conflicts. Should be pretty straight foward :)

**Comment by DonaldLika** [comment]
@aemc  ok working on it

**Comment by BloodlessBaron** [comment]
FYI, [Dependabot](https://github.com/marketplace/dependabot) on the GitHub Marketplace will check your package.json periodically and create a pull request to update your dependencies any time they update. You can even have them automatically merged if they pass all your checks. It's free for open source too.

**Comment by aemc** [comment]
@BloodlessBaron Thanks! I'll look into it.
